require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  # SuggestExtensions: false
  Exclude:
  - vendor/bundle/**/*
  - db/migrate/*
  - node_modules/node-sass
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Exclude:
    - 'db/*'
Metrics/ExampleLength:
  Exclude:
    - 'spec/requests/api/v1/*'

RSpec/MultipleExpectations:
  Max: 10
#一旦指摘無視して実装進めたいため記述
RSpec/AnyInstance:
  Enabled: false
