require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  # SuggestExtensions: false
  TargetRubyVersion: 3.1.1
  Exclude:
    - "node_modules/**/*" # rubocop config/default.yml
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema.rb"
    - "bin/bundle"
    - db/migrate/*
  # Exclude:
  # - vendor/bundle/**/*


Metrics/BlockLength:
  Exclude:
    - 'db/*'
# Metrics/ExampleLength:
#   Exclude:
#     - 'spec/requests/api/v1/*'
#     - 'spec/requests/api/v1/**/*'

RSpec/MultipleExpectations:
  Max: 10
#一旦指摘無視して実装進めたいため記述
RSpec/AnyInstance:
  Enabled: false
Style/GlobalVars:
  Enabled: false
