require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  # SuggestExtensions: false
  Exclude:
  - vendor/bundle/**/*
  - db/migrate/*
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Exclude:
    - 'db/*'

RSpec/MultipleExpectations:
  Max: 5
